# Mod Properties
mod_version=1.1.2+26.1.2
maven_group=net.vanillaoutsider.hyperscreenshots
archives_base_name=vanilla-outsider-hyper-screenshots

# Dependencies
minecraft_version=26.1.2
yarn_mappings=26.1.2+build.1
loader_version=0.19.1
fabric_version=0.145.4+26.1.2

# Optional Dependencies
yacl_version=3.8.1+1.21.4-fabric
modmenu_version=14.0.0-rc.2
